development:
  host: 127.0.0.1
  port: 6379
  db: 0
  namespace: myFR
test:
  host: 127.0.0.1
  port: 6379
  db: 0
  namespace: myFRTest
staging:
  host: redis.fr2.ec2.internal
  port: 6379
  db: 0
  namespace: myFR
officialness_staging:
  host: redis.fr2.ec2.internal
  port: 6379
  db: 0
  namespace: myFR
production:
  host: redis.fr2.ec2.internal
  port: 6379
  db: 0
  namespace: myFR
