aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

circle_ci:
  reg_gov_build_token: <%= ENV['CIRCLE_CI_REG_GOV_BUILD_TOKEN'] %>

data_dot_gov:
  api_key: <%= ENV['DATA_DOT_GOV_API_KEY'] %>

email_salt: <%= ENV['EMAIL_SALT'] %>

jwt_secret: <%= ENV['JWT_SECRET'] || "development_secret_key" %>
omniauth:
  oidc_url: <%= ENV['OIDC_URL'] || "#{Settings.services.fr_profile_url}/profile" %>
  oidc_application_id: <%= ENV['OIDC_APPLICATION_ID'] || '0a8a19a0209073fc37e7c3ad36d765e64773f938590c3c0739851e7cf114b2af' %>
  oidc_secret: <%= ENV['OIDC_SECRET']|| 'ef3eedaff9679ccf655c9197c5841cff9cb4923a3064d3735ec7ef4df7f40e38' %>
  oidc_redirect_url: <%= ENV['OIDC_REDIRECT_URL'] || 'http://localhost:3000/auth/ofr/callback' %>

recaptcha:
  public: <%= ENV['RECAPTCHA_PUBLIC'] %>
  private: <%= ENV['RECAPTCHA_PRIVATE'] %>

redis:
  host: <%= ENV['REDIS_PORT_6379_TCP_ADDR'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT_6379_TCP_PORT'] || 6379 %>
  db: <%= ENV['REDIS_DB'] || 0 %>

sendgrid:
  username: <%= ENV['SENDGRID_USERNAME'] %>
  password: <%= ENV['SENDGRID_PASSWORD'] %>

session_secret_token: <%= ENV['RAILS_SESSION_KEY'] %>
