# urls for mailers, redirects, etc - where routes aren't available
app_url: 'https://www.federalregister.gov'
canonical_host: 'https://www.federalregister.gov'
fr_comment_url: 'https://www.federalregister.gov/my/comments'


external_modal_domain_whitelist:
  - "www.archives.gov"
  - "www.govinfo.gov"
  - "federalregister.tenderapp.com"
  - "s3.amazonaws.com/public-inspection."
  - "s3.amazonaws.com/archives."

feature_flags:
  events_search: false
  fr_index_pdfs: false
  unified_agenda:
    search: false
  regulations_dot_gov:
    submit_comments: <%= ENV["REG_GOV_SUBMIT_COMMENTS"] || false %>
  regulatory_plan: false
  # google charts image api is deprecated - reimplement in js
  sparklines:
    agencies: false
    topics: false
    suggested_searches: false
    my_fr:
      subscriptions: false
  search:
    location: true

federal_register:
  api_url: '<%= ENV["FR_API_URL"] %>'
  base_url: '<%= ENV["FR_BASE_URL"] %>'
  internal_api_url: '<%= ENV["FR_INTERNAL_API_URL"] %>'
  internal_base_url: '<%= ENV["FR_INTERNAL_BASE_URL"] %>'

federal_register_archives:
  api_url: '<%= ENV["FR_ARCHIVES_API_URL"] %>'

# generic switch for deciding when to raise exception or notify honeybadger
notify_honeybager: true

officialness:
  start_date: 2025-05-01

regulations_dot_gov:
  base_uri: <%= ENV["REG_GOV_BASE_URL"] || 'https://api.data.gov/TEST/regulations/v3' %>
  # don't output calls to reg.gov in stdout
  debug_output_enabled: false


# document page full text rendering - false means use esi's
render_documents_from_raw_xml: false

rss_helper:
  url: "https://www.federalregister.gov"

varnish:
  host: <%= ENV["VARNISH_ADDR"] || 'varnish' %>
  port: 6082

services:
  fr_profile_url: '<%= ENV["FR_PROFILE_BASE_URL"] %>'
