app:
  allow_bot_traffic: true
  csp:
    report_only: true

regulations_dot_gov:
  api_base_url: https://api.regulations.gov/v4

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  image_variants: img.federalregister.gov
  private_images: private.images.federalregister.gov
  public_images: images.federalregister.gov
